name: Deploy
on:
  workflow_dispatch:
    inputs:
      target:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Git config
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Deploy
        run: bash ./bin/deploy.sh ${{ github.event.inputs.target }}
