name: Deploy
on:
  push:
  workflow_dispatch:
jobs:
  matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mxschmitt/action-tmate@v3
      - id: jobs
        run: |
          echo '::set-output name=jobs::{"name": ["foo", "bar", "baz"]}'
    outputs:
      jobs: ${{ steps.jobs.outputs.jobs }}
  foo:
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      matrix: ${{ fromJSON(needs.matrix.outputs.jobs) }}
    steps:
      - run: echo ${{ matrix.name }}
