name: Deploy
on:
  workflow_dispatch:
    inputs:
      target:
jobs:
  deploy:
    if: startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Git config
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          touch foo
          git add foo
          git commit -m hi
          git push origin main
